version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "latest"
  apt_packages:
    - libgl1-mesa-dev
    - xvfb
  jobs:
    create_environment:
      - asdf plugin add pixi
      - asdf install pixi latest
      - asdf global pixi latest
    pre_install:
      # keep checkout untainted from RTD to ensure correct setuptools-scm version
      - git stash || true
    install:
      - pixi install --cwd geovista --frozen --environment docs
    post_install:
      - git stash pop || true
      - pixi run --cwd geovista --frozen --environment docs geovista download --operational --decompress
      - cp -a locale geovista/docs/src/
    build:
      html:
        - pixi run --frozen --environment docs sphinx-build -T -b html -d _build/doctrees docs/src $READTHEDOCS_OUTPUT/html --cwd geovista

submodules:
  include: all

sphinx:
  configuration: geovista/docs/src/conf.py
  fail_on_warning: false
