version: 2

build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-22.9
  apt_packages:
    - libgl1-mesa-dev
    - xvfb
  jobs:
    post_install:
      - geovista download --operational --decompress

submodules:
  include:
    - geovista
  recursive: true

conda:
  environment: geovista/requirements/locks/rtd.yml

sphinx:
  configuration: conf.py
  fail_on_warning: false

python:
  install:
    - method: pip
      path: geovista
      extra_requirements:
        - cmap
        - docs
